version: '3.1'
services:
  todo-frontend:
    #image: hsr_distributedsystems_24_todo_frontend:0.1 
    build:
      context: todo-frontend
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    networks:
      - todo-network
    environment:
      - BACKEND_URL=todo-backend

  todo-backend:
    #image: hsr_distributedsystems_24_todo_backend:0.1 
    build:
      context: todo-backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - todo-network
    depends_on:
      - todo-database
    environment:
      - DATABASE_URL=todo-database

  todo-database:
    #image: hsr_distributedsystems_24_todo_database:0.1
    build:
      context: todo-database
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    networks:
      - todo-network

networks:
  todo-network: {}